# Generated by Django 3.0.4 on 2020-03-23 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipapp', '0009_auto_20200323_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='recipe',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.CharField(max_length=255),
        ),
    ]
