# Generated by Django 3.0.4 on 2020-03-23 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipapp', '0010_auto_20200323_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='recipe',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='recipapp.Recipe'),
            preserve_default=False,
        ),
    ]
