# Generated by Django 3.0.4 on 2020-03-23 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipapp', '0011_ingredient_recipe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={},
        ),
    ]
